-- Checkpoint 6: in-app notification inbox.
-- Rows can be generated by future app/RPC/Edge Function workflows and are read by the app without realtime.

do $$
begin
  create type public.notification_type as enum (
    'review_questions',
    'discussion_posts',
    'rabbi_answers',
    'uploads',
    'join_requests',
    'system'
  );
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  chaburah_id uuid references public.chaburos(id) on delete cascade,
  type public.notification_type not null,
  title text not null,
  body text not null,
  action_route text,
  action_params jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_unread_idx
  on public.notifications (user_id, created_at desc)
  where read_at is null;

alter table public.notifications enable row level security;

revoke all on public.notifications from anon, authenticated;
grant select, insert, update, delete on public.notifications to authenticated;

drop policy if exists notifications_select_self on public.notifications;
create policy notifications_select_self
on public.notifications
for select
to authenticated
using (user_id = (select auth.uid()));

drop policy if exists notifications_insert_self_or_global_admin on public.notifications;
create policy notifications_insert_self_or_global_admin
on public.notifications
for insert
to authenticated
with check (
  user_id = (select auth.uid())
  or private.is_global_admin()
);

drop policy if exists notifications_update_self on public.notifications;
create policy notifications_update_self
on public.notifications
for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

drop policy if exists notifications_delete_self on public.notifications;
create policy notifications_delete_self
on public.notifications
for delete
to authenticated
using (user_id = (select auth.uid()));
